# Generated by Django 6.0.1 on 2026-04-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donneemeteo',
            name='humidite',
        ),
        migrations.AddField(
            model_name='donneemeteo',
            name='altitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
